### ISSUE TITLE
Donation pages

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#19]
- [x] Find solution for annual donation in FBH new page/donation form

This page does not currently exists and needs to be created in-line with the template.

- [x] Needs to have a pelecard iframe
- [x] Needs to support annual recurring payment

https://projects.invisionapp.com/d/main#/projects/prototypes/10056886

**Comment by ibanner** [comment]
@nirgoldberg I've stared putting the front-end together. As far as the back-end goes, I'm going to need to create a new CPT, along with some ACF to make the UX similar to how you manage content. Would you prefer I'd pack everything in a plugin, or integrate my code to the theme files?

**Comment by nirgoldberg** [comment]
Hi @ibanner,
1. Please explain why you need to create a new CPT. As far as I understand the design, no CPT is needed here. In any case, I wouldn't prefer pack this in a plugin.
2. Absolutely not define a new image size, as it will influence all future media upload.

**Comment by ibanner** [comment]
@nirgoldberg I believe you're going to need a way to document the donations, mainly if you wish to offer donors to set up an annual donation.

As I see it, there are 2 approaches here:

1. **Under WooCommerce:** Donations will be set up as a virtual product. That would include installing some WC extensions to support the requirements, e.g. [**Name Your Price**](https://woocommerce.com/products/name-your-price/) for custom donation sums, and **[WooSubsciptions](https://woocommerce.com/products/woocommerce-subscriptions/)** for annual donations. No new CPT required. a different gateway would also be needed for this "product" so that the correct receipt (rather than tax invoice) will be sent to the donor.

2. **Independent Setup:** Transactions are sent directly to Pelecard (via iFrame). This way - in my opinion - a CPT is needed to log all donations and manage the annuals. I'm guessing you'll also want to analyse the donations list to monitor the feature performance. 

I had the feeling this is the setup you had in mind (rather than via WC). Am I wrong? Do you see another possible approach?

No plugin, no new image size, got it :)

**Comment by ibanner** [comment]
Pull request made today #36 (pending review)

**Comment by TheGrandVizier** [comment]
Rest of treatment will be in specific issues.
