### ISSUE TITLE
Customize the email the user recieves from iCount upon donation completed

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-bh#49]
The email a user receives after donating is currently the default produced by icount.
In theory, we can customize this email if we so desire.
Here is the stock, default text:

http://prntscr.com/gjdayp

**Comment by TheGrandVizier** [comment]
@nuritgazit 
is this something you'd be interested in?

**Comment by nuritgazit** [comment]
Absolutely, Hagay should do it

**Comment by ibanner** [comment]
@TheGrandVizier @nuritgazit If you send me the texts, I'll take care of the setup on iCount.

**Comment by nuritgazit** [comment]
@hagayk please help with the text here, urgently

**Comment by hagayk** [comment]
Donation Receipt

Beit Hatfutsot – Because you are Part of the Story!

We, at Beit Hatfutsot - Museum of the Jewish People, would like to thank you and welcome you into our family of friends. With your generous donation we can sponsor the likes of family tours, children’s classes tours and educational seminars and visits for groups of soldiers including transportation, lunch and educational seminars. We couldn't do it without you!

**Comment by ibanner** [comment]
@nuritgazit Thanks. I need it in Hebrew too.

As suggested before, I think the copy should also:

1. State that this is a digitally signed receipt.
2. Mention that if you asked for a Tribute Certificate, it will be emailed to you in a few days (or whatever you want to promise there...)

**Comment by hagayk** [comment]
Digitally Signed Donation Receipt

Beit Hatfutsot – Because you are Part of the Story!

We, at Beit Hatfutsot - Museum of the Jewish People, would like to thank you and welcome you into our family. With your generous donation we can sponsor the likes of family tours, children’s classes tours and educational seminars and visits for groups of soldiers. We couldn't do it without you! 
Please note: If asked for A Tribute Certificate, it will be emailed to you in A few days.

**Comment by hagayk** [comment]
קבלה חתומה דיגיטלית

בית התפוצות - כי אתם חלק מהסיפור!

אנחנו בבית התפוצות - מוזיאון העם היהודי, רוצים להודות לך מעומק הלב ולקבל אותך בזרועות פתוחות אל משפחתנו. בעזרת התרומה הנדיבה שלך, נוכל לממן פעילות מגוונות אצלנו במוזיאון כגון: סיורי משפחות, שיעורים וסדנאות לכיתות בית ספר וסמינרים חינוכיים לחיילי צה"ל ועולים חדשים. את כל זה לא היינו יכולים לעשות בלעדיך!

**Comment by hagayk** [comment]
שימו לב: אם ביקשתם שנצרף תעודת הוקרה היא תישלח במייל תוך מספר ימים

**Comment by ibanner** [comment]
Template setup completed on iCount.
