### ISSUE TITLE
Change our logo to the 40-70 logo

### ISSUE THREAD

**Issue by nuritgazit** [Beit-Hatfutsot/wp-bh#72]
On the 1/1/2018 the header in all sites (bh museum, DBs, shop, nobel, chezk, austria, rav-dori) to the new header with 70-40.
@Netush please add the new logo's location

**Comment by Netush** [comment]
SVG & PNG Files you can find here:
https://www.dropbox.com/sh/3zka61lv8w8vfve/AADC0OLaxbt0puqYBQH7Lof8a?dl=0

BH-Logo4070-Heb-Update
BH-Logo4070-Eng-Update

**Comment by nuritgazit** [comment]
@ibanner, please take this

**Comment by ibanner** [comment]
Should these files just replace the existing ones? I mean, same sizes, same locations? If not, I'm going to need more specifications on this.

Also, can someone (@TheGrandVizier ?) please send me a screenshot of the Header/Footer options I need to set in order to view the Header properly? At the moment my local site displays no header at all.

**Comment by TheGrandVizier** [comment]
No clue.
@nirgoldberg  maybe?

**Comment by nirgoldberg** [comment]
@ibanner, let's talk about it next week.

**Comment by ibanner** [comment]
@nirgoldberg I thought I'd just upload these files to the SVGS directory, rename them to 'logo-en' and 'logo-he' and rename the current files to something temporary. Does that sound ok?

**Comment by nirgoldberg** [comment]
There are few more things to do.
Let's do it online together.

**Comment by ibanner** [comment]
Note to self: copy the new "viewbox" value to 'shape-logo-en.php' and 'shape-logo-he.php'
